# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token: # unsecured endpoint to authenticate
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/api # this should match anything that doesn't match on earlier rules (won't break debug toolbar)
            fos_oauth: true
            stateless: true
            anonymous: true

        main:
            pattern: ^/
            anonymous: true

    access_control:
      - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, role: ROLE_USER }
      - { path: ^/, role: ROLE_NO_ACCESS }
