# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/RexSoftwareTest/ApiBundle available to be used as services
    RexSoftwareTest\ApiBundle\:
            resource: '../../src/RexSoftwareTest/ApiBundle/*'
            # you can exclude directories or files
            # but if a service is unused, it's removed anyway
            exclude: '../../src/RexSoftwareTest/ApiBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    RexSoftwareTest\ApiBundle\Controller\:
        resource: '../../src/RexSoftwareTest/ApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    repository.access_token:
        class: RexSoftwareTest\ApiBundle\Repository\AccessTokenRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - RexSoftwareTest\ApiBundle\Entity\AccessToken

    repository.auth_code:
        class: RexSoftwareTest\ApiBundle\Repository\AuthCodeRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - RexSoftwareTest\ApiBundle\Entity\AuthCode

    repository.client:
        class: RexSoftwareTest\ApiBundle\Repository\ClientRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - RexSoftwareTest\ApiBundle\Entity\Client

    repository.refresh_token:
        class: RexSoftwareTest\ApiBundle\Repository\RefreshTokenRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - RexSoftwareTest\ApiBundle\Entity\RefreshToken

    repository.user:
        class: RexSoftwareTest\ApiBundle\Repository\UserRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - RexSoftwareTest\ApiBundle\Entity\User

    repository.movie:
        class: RexSoftwareTest\ApiBundle\Repository\MovieRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - RexSoftwareTest\ApiBundle\Entity\Movie

    repository.actor:
        class: RexSoftwareTest\ApiBundle\Repository\ActorRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
          - RexSoftwareTest\ApiBundle\Entity\Actor
